// <auto-generated />
namespace BTLTQL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Create_table_Account : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Create_table_Account));
        
        string IMigrationMetadata.Id
        {
            get { return "202203090224184_Create_table_Account"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
